feat: add initial puppet example with package.json and index.ts
wechatferry/wechatferry pull request #20
Opened 2024-12-13 12:19 UTC by atorber

增加使用wechaty的示例代码

2024-12-13 14:15 UTC, KeJunMao requested changes

2024-12-13 14:15 UTC, KeJunMao commented on examples/puppet/package.json
> +  "name": "agent",
puppet

2024-12-13 14:15 UTC, KeJunMao commented on examples/puppet/src/index.ts
> +const logger = useLogger('agent-example')
puppet

2024-12-15 14:45 UTC, KeJunMao requested changes
感谢你的努力。

你能单独开一个pr来修改 lz4 的依赖吗？

2024-12-15 14:45 UTC, KeJunMao commented on package.json
> +  "version": "0.0.24",
不要 变更版本号

2024-12-15 14:45 UTC, KeJunMao commented on packages/agent/src/utils.ts
> +import zlib from 'zlib'
zlib 与 lz4 算法一样吗？

2024-12-16 08:15 UTC, closed without merging

2025-03-01 08:31 UTC, 951871040 commented
作者大大可以替换下lz4这个库吗？这个库已经停更几年了，新的node好像已经不支持这个库了

2025-03-01 10:04 UTC, KeJunMao commented
有与 lz4  算法一样的库吗